let dummyItemsList = [
  {
    id: 1,
    name: 'Bananas',
    price: 5.99,
    quantity: 'per dozen',
    image: require('../assets/banana.png'),
    attributes: ['fruit', 'healthy'],
  },
  {
    id: 2,
    name: 'Apples',
    price: 1.29,
    quantity: 'per pound',
    image: require('../assets/apple.png'),
    attributes: ['fruit', 'healthy'],
  },
  {
    id: 3,
    name: 'Oranges',
    price: 1.65,
    quantity: 'per pound',
    image: require('../assets/Orange.jpg'),
    attributes: ['fruit', 'healthy'],
  },
  {
    id: 4,
    name: 'Bread',
    price: 2.49,
    quantity: 'per loaf',
    image: require('../assets/bread.jpeg'),
    attributes: ['bread', 'bakery'],
  },
  {
    id: 15,
    name: 'Milk',
    price: 2.99,
    quantity: 'per gallon',
    image: require('../assets/milk.png'),
    attributes: ['dairy', 'beverage', 'breakfast'],
  },
  {
    id: 16,
    name: 'Eggs',
    price: 1.99,
    quantity: 'per dozen',
    image: require('../assets/eggs.jpg'),
    attributes: ['dairy', 'protein', 'breakfast'],
  },
  {
    id: 18,
    name: 'Chicken',
    price: 4.99,
    quantity: 'per pound',
    image: require('../assets/chicken.jpg'),
    attributes: ['meat', 'protein'],
  },
  {
    id: 27,
    name: 'Rice',
    price: 3.49,
    quantity: 'per pound',
    image: require('../assets/rice.jpeg'),
    attributes: ['grains', 'staple'],
  },
  {
    id: 20,
    name: 'Pasta',
    price: 1.99,
    quantity: 'per pack',
    //image: require('../assets/milk.png'),
    attributes: ['grains', 'staple'],
  },
  {
    id: 10,
    name: 'Cereal',
    price: 3.99,
    quantity: 'per box',
    image: require('../assets/cereal.jpeg'),
    attributes: ['grains', 'breakfast'],
  },
  {
    id: 11,
    name: 'Yogurt',
    price: 2.49,
    quantity: 'per cup',
    image: require('../assets/yogurt.jpg'),
    attributes: ['dairy', 'breakfast'],
  },
  {
    id: 12,
    name: 'Cheese',
    price: 3.99,
    quantity: 'per pound',
    image: require('../assets/cheese.jpeg'),
    attributes: ['dairy'],
  },
  {
    id: 13,
    name: 'Butter',
    price: 2.29,
    quantity: 'per stick',
    //image: require('../assets/milk.png'),
    attributes: ['dairy', 'spread'],
  },
  {
    id: 19,
    name: 'Tomato',
    price: 0.99,
    quantity: 'per pound',
    //image: require('../assets/milk.png'),
    attributes: ['vegetable'],
  },
];
export default dummyItemsList;
